/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'felipe' at '10/16/16 7:06 PM' with Gradle 2.10
 *
 * @author felipe, @date 10/16/16 7:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
